image:
  repository: ghcr.io/asamk/signal-cli
  tag: "0.14.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  size: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
